[image_validation]
image_size = 3145728
image_formats = ["jpg", "png","jpeg"]
image_size_error = "Please upload an image file smaller than 3MB."
image_format_error = "Please upload a JPG or PNG image."

[database]
engine = 'django.db.backends.postgresql'
name =  'blog_db'
user = 'postgres'
password = 'admin'
host = '127.0.0.1'
port = '5432'

[newsapi]
apikey = 'bf8802a3ab0c43609504d73616d6d5be'
url = 'https://newsapi.org/v2/top-headlines?country=in&apiKey='